#if defined(USE_TLS) && defined(USE_MQTT_TLS_CA_CERT)

char AmazonClientCert[857];
char AmazonPrivateKey[45];

static const char serverCert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIBCzCBtgIJAL0cewa9T9XLMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNVBAYTAktS
MB4XDTIyMDExMzAyNDEyN1oXDTMzMDQwMTAyNDEyN1owDTELMAkGA1UEBhMCS1Iw
XDANBgkqhkiG9w0BAQEFAANLADBIAkEAuC6rUj2m0phpCkZVV9U//v4H8/3vaHck
dG9f0yMpZyoXsZBaIePPfBjLW5kg16Fj+eQP0IKhWJ3LzNTVAXl1nwIDAQABMA0G
CSqGSIb3DQEBCwUAA0EAnTlMjfsHiNwFlxIjgp+r0CpqE6+o+WlnjuUCYi3ZnmNe
eclX5v75TKvJQ4nrDqQfTwqaO+iNs/DJDqsVpWZZEQ==
-----END CERTIFICATE-----
)EOF";

static const char serverKey[] PROGMEM =  R"EOF(
-----BEGIN PRIVATE KEY-----
MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAuC6rUj2m0phpCkZV
V9U//v4H8/3vaHckdG9f0yMpZyoXsZBaIePPfBjLW5kg16Fj+eQP0IKhWJ3LzNTV
AXl1nwIDAQABAkBV492c8oczOkPxuK7f0OCRJyHKVKcqjjT/31hOe9048AuYFdio
8599iR+EMYu1499Z2VLtkPyePTsraKwuSufhAiEA3wIezIGyjGL9enn/RSJoIKuk
RfBXLl60MsbDeJ6a84cCIQDTbhy6NxDon4JwA4Q/dX/ZVGADtzn9MYzGeAFQqvsj
KQIgMqIonAZWo8lWBBju/KNzQPe3tKl9Ieoev+ihOSHJzMECIEmuavZ+MDdRN0y/
/Pt8gDSF0fwZg2z4Mp4LvjGVlHWZAiA5Qd0a1Jt9to6tlOpilS0uW4HdoW8CK6pA
Ng9m8M/5+Q==
-----END PRIVATE KEY-----
)EOF";


#endif // defined(USE_TLS) && defined(USE_MQTT_TLS_CA_CERT)
