name: Tasmota ESP32 CI

on: [push, pull_request]

jobs:
  tasmota32:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: | 
        cp platformio_override_sample.ini platformio_override.ini
        platformio run -e tasmota32
   
