name: Build_firmware_ziot_tasmota

on:
  push:
    branches: [ "ZIoT-Tasmota-master" ]
    paths-ignore:
    - '.github/**'
    - '**.md'
  pull_request:
    branches: [ "ZIoT-Tasmota-master" ]
    paths-ignore:
    - '.github/**'
    - '**.md'

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'zigbang/Tasmota'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - ziot-sonoff-minimal
          - ziot-sonoff
          - smart-roll-esp-wrover
          - ziot-uart-module
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ZIoT-Tasmota-develop
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -U platformio
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.variant }}
      - uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ./build_output
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            $(ls ./build_output/firmware/${{ matrix.variant }}-*.bin) s3://ziot-dev-tasmota-firmware-bucket/${{ matrix.variant }}/
